# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pluginrepo', '0005_plugin_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginVersionedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=100)),
                ('changeNotes', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=2000)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioned_files', to='pluginrepo.Plugin')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
