# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginjar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginversionedfile',
            name='path',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
