# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
