# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0002_plugin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='name',
            field=models.CharField(default='Demo Plugin', max_length=50),
            preserve_default=False,
        ),
    ]
