# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0003_plugin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
    ]
