# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0004_pluginvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to='pluginrepo.PluginVendor'),
            preserve_default=False,
        ),
    ]
