# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0005_plugin_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='strId',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='pluginvendor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pluginvendor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pluginvendor',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
