# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginrepo', '0006_auto_20170915_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugin',
            name='iconUrl',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
